[app]
name = "maudit"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = 8090

[app.grpc]
host = "127.0.0.1"
port = 18090

[mcenter]
address = "127.0.0.1:18010"
client_id = "xx"
client_secret = "xx"

[mongodb]
endpoints = ["127.0.0.1:27017"]
database = "maudit"

[log]
level = "debug"

[log.file]
enable = true
file_path = "logs/maudit.log"